### ISSUE TITLE
Timezone should not be Europe/Amsterdam

### ISSUE THREAD

**Issue by wido** [PCextreme/packer-templates#30]
All templates currently have Europe/Amsterdam hardcoded in them.

This might have been a good idea at the beginning, but with Aurora Compute being available in Miami, Tokyo and Los Angeles this doesn't apply any more.

We might need to figure out a method where the template detects the local timezone and reconfigures based on that.

**Comment by kevindierkx** [comment]
@loekg Has resolved this in: 2dc8db793385b945d5ca6726610122a204bf3db4
Templates are built with UTC as default and can be set to the local timezone using CloudInit:
```
// For example
timezone: Europe/Amsterdam
```
