### ISSUE TITLE
SELINUX blocks cloud-set-guest-password to start on boot stage for Fedora 24 Templates

### ISSUE THREAD

**Issue by ozhanka** [PCextreme/packer-templates#32]
Hi;
We noticed that SELINUX blocks cloud-set-guest-password to start at boot stage. So Fedora 24 templates/vm's could not get and set any password from vr. To solve the issue either take SELINUX to permissive mode or we need to write some selinux rules for cloud-set-guest-password script.

Thanks
Özhan

Jul 19 15:26:10 Fed24Test01.localdomain cloud[831]: Failed to get password from any server
Jul 19 15:26:10 Fed24Test01.localdomain systemd[1]: cloud-set-guest-password.service: Main process exited, code=exited, status=1/FAILURE
Jul 19 15:26:10 Fed24Test01.localdomain systemd[1]: Failed to start CloudStack Guest Password Reset.
-- Subject: Unit cloud-set-guest-password.service has failed
-- Defined-By: systemd
## -- Unit cloud-set-guest-password.service has failed.

-- The result is failed.
Jul 19 15:26:10 Fed24Test01.localdomain systemd[1]: cloud-set-guest-password.service: Unit entered failed state.
Jul 19 15:26:10 Fed24Test01.localdomain audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='un
Jul 19 15:26:10 Fed24Test01.localdomain systemd[1]: cloud-set-guest-password.service: Failed with result 'exit-code'.

**Comment by RPDiep** [comment]
Thanks Özhan for reporting this. We'll look into this and write the necessary exception rules for SElinux.
